menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/trishhyles
    Lofter: http://vvalkyrja.lofter.com
    About: /about/

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: vvalkyrja
duoshuo:

# Analytics
# google-analytics:
ga: UA-46701977-3

# Copyright Infomation
startyear: 2017
