menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/trishhyles
    GitHub: https://github.com/zhichaopro
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-46701977-3

# Copyright Infomation
startyear: 2017
